import os

from snakemake.utils import min_version

min_version("8.0")


# Built-in defaults, part of the workflow itself -- not meant to be edited
# or even looked at for a first run. See "Tool versions" / "HPC / SLURM" in
# the README to override any of these instead.
configfile: "workflow/default-config/versions.yaml"
configfile: "workflow/default-config/resources.yaml"

# The one file you actually need to edit to run an analysis.
configfile: "config/config.yaml"

# Optional user overrides: only loaded if you create them yourself, and only
# need to contain the keys you want to change -- deep-merged on top of the
# built-in defaults above. See "Tool versions" / "HPC / SLURM" in the README.
if os.path.exists("config/versions.yaml"):

    configfile: "config/versions.yaml"


if os.path.exists("config/resources.yaml"):

    configfile: "config/resources.yaml"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/align.smk"
include: "rules/strandedness.smk"
include: "rules/tetranscripts.smk"
include: "rules/qc.smk"


rule all:
    input:
        all_tecount_tables(),
        all_diffexp_outputs(),
        "results/qc/multiqc_report.html",


rule star_index_only:
    # Convenience target: just (re)build the STAR genome index.
    input:
        config["star"]["index"],


rule strandedness_only:
    # Convenience target: run just alignment + strandedness auto-detection
    # for samples that need it (effective mode "auto"), useful for
    # sanity-checking a new sample sheet before quantification.
    input:
        expand("results/rseqc/{sample}/strandedness.txt", sample=AUTO_SAMPLES),
