name: rnaseq-star-tetranscripts
channels:
  - conda-forge
  - bioconda
dependencies:
  - nextflow
  - star
  - samtools
  - multiqc
  - rseqc
  - tetranscripts
  - ucsc-gtftogenepred
  - ucsc-genepredtobed
  - python >=3.9
  - pandas
