name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rnaseq-star-tetranscripts
          environment-file: environment.yaml
          channel-priority: flexible
      - shell: bash -l {0}
        run: snakemake --configfile config/test.yaml --cores 2

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rnaseq-star-tetranscripts
          environment-file: environment.yaml
          channel-priority: flexible
      - shell: bash -l {0}
        run: snakemake --configfile config/test.yaml --cores 2
